apiVersion: v1
kind: Service
metadata:
  name: keel-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: keel
  ports:
    - port: {{keel_port}}
      targetPort: {{keel_port}}
      nodePort: {{keel_node_port}}
